# -*- coding: utf-8 -*-
"""CC(Artical)Second.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCYpeAgOIQbS7ix6MpSeTL_CbvjE27SM

Import necessary modules
"""

import numpy as np
import os
import pandas as pd
from PIL import Image
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import shutil

print(os.getcwd())
base_dir = "/content/drive/MyDrive/Sahajuddin/CC(Artical)"
categories = ["im_Dyskeratotic", "im_Koilocytotic", "im_Metaplastic",
              "im_Parabasal", "im_Superficial-Intermediate"]

sns.set(style="whitegrid")

for category in categories:
    category_path = os.path.join(base_dir, category)
    if os.path.exists(category_path):
        image_count = len(os.listdir(category_path))
        print(f"Category: {category}, Image Count: {image_count}")
    else:
        print(f"Category: {category} does not exist in {base_dir}")

import os
from PIL import Image

def resize_image_and_scale_coords(image_path, cyt_dat_path, nuc_dat_path, output_category_dir):
    image = Image.open(image_path)
    original_width, original_height = image.size

    # Resize image to 224x224 and save it
    resized_image = image.resize((224, 224))
    resized_image.save(os.path.join(output_category_dir, os.path.basename(image_path)))

    # Calculate scaling factors
    scale_x = 224 / original_width
    scale_y = 224 / original_height

    # Process .dat files (cytoplasm and nucleus coordinates)
    for dat_path in [cyt_dat_path, nuc_dat_path]:
        scaled_coords = []
        with open(dat_path, 'r') as file:
            for line in file.readlines():
                x, y = map(float, line.strip().split(','))
                scaled_x = x * scale_x
                scaled_y = y * scale_y
                scaled_coords.append(f"{scaled_x:.2f},{scaled_y:.2f}")

        output_dat_path = os.path.join(output_category_dir, os.path.basename(dat_path))
        with open(output_dat_path, 'w') as file:
            file.write("\n".join(scaled_coords))

def process_dataset(data_dir, output_dir, categories):
    os.makedirs(output_dir, exist_ok=True)

    for category in categories:
        input_category_dir = os.path.join(data_dir, category, "CROPPED")  # ✅ Fixed path
        output_category_dir = os.path.join(output_dir, category)
        os.makedirs(output_category_dir, exist_ok=True)

        # Check if input folder exists
        if not os.path.exists(input_category_dir):
            print(f"❌ Warning: {input_category_dir} does not exist. Skipping...")
            continue  # Skip this category if folder not found

        # Process images and corresponding .dat files
        for file in os.listdir(input_category_dir):
            if file.endswith('.bmp'):
                prefix = file.split('.bmp')[0]
                image_path = os.path.join(input_category_dir, file)
                cyt_dat_path = os.path.join(input_category_dir, f"{prefix}_cyt.dat")
                nuc_dat_path = os.path.join(input_category_dir, f"{prefix}_nuc.dat")

                if os.path.exists(cyt_dat_path) and os.path.exists(nuc_dat_path):
                    resize_image_and_scale_coords(image_path, cyt_dat_path, nuc_dat_path, output_category_dir)

# Define paths
data_dir = "/content/drive/MyDrive/Sahajuddin/CC(Artical)"
output_dir = "/content/drive/MyDrive/Sahajuddin/OutputCC(Artical)"
categories = ["im_Dyskeratotic", "im_Koilocytotic", "im_Metaplastic", "im_Parabasal", "im_Superficial-Intermediate"]

# Run the dataset processing
process_dataset(data_dir, output_dir, categories)
print("✅ Dataset processing complete!")

def visualize_resized_image_with_coords(image_path, dat_file, label):
    # Load image and coordinates
    image = Image.open(image_path)
    coordinates = []
    with open(dat_file, 'r') as file:
        for line in file.readlines():
            x, y = map(float, line.strip().split(','))
            coordinates.append((x, y))

    # Plot the image and points
    plt.imshow(image)
    x_coords, y_coords = zip(*coordinates)
    plt.scatter(x_coords, y_coords, c='red', label=label)
    plt.title(f"Image: {os.path.basename(image_path)}")
    plt.legend()
    plt.show()

image_path = f"{output_dir}/im_Parabasal/001_01.bmp"
cyt_dat_path = f"{output_dir}/im_Parabasal/001_01_cyt.dat"
nuc_dat_path = f"{output_dir}/im_Parabasal/001_01_nuc.dat"

visualize_resized_image_with_coords(image_path, cyt_dat_path, "Cytoplasm Points")
visualize_resized_image_with_coords(image_path, nuc_dat_path, "Nucleus Points")

import os
import matplotlib.pyplot as plt
from PIL import Image

def visualize_resized_image_with_coords(image_path, dat_file, label):
    if not os.path.exists(image_path):
        print(f"❌ Image not found: {image_path}")
        return

    if not os.path.exists(dat_file):
        print(f"❌ Coordinate file not found: {dat_file}")
        return

    # Load image and coordinates
    image = Image.open(image_path)
    coordinates = []
    with open(dat_file, 'r') as file:
        for line in file.readlines():
            x, y = map(float, line.strip().split(','))
            coordinates.append((x, y))

    # Plot the image and points
    plt.imshow(image)
    if coordinates:
        x_coords, y_coords = zip(*coordinates)
        plt.scatter(x_coords, y_coords, c='red', label=label)
    plt.title(f"Image: {os.path.basename(image_path)}")
    plt.legend()
    plt.show()

# ✅ Updated paths after checking folder structure
image_path = f"{base_dir}/im_Parabasal/CROPPED/001_01.bmp"
cyt_dat_path = f"{base_dir}/im_Parabasal/CROPPED/001_01_cyt.dat"
nuc_dat_path = f"{base_dir}/im_Parabasal/CROPPED/001_01_nuc.dat"

# Run visualization with error handling
visualize_resized_image_with_coords(image_path, cyt_dat_path, "Cytoplasm Points")
visualize_resized_image_with_coords(image_path, nuc_dat_path, "Nucleus Points")

dataset = output_dir
image_counts = {}

for category in categories:
    category_path = os.path.join(dataset, category)
    image_counts[category] = len([f for f in os.listdir(category_path) if f.endswith(('.bmp', '.jpg', '.png'))])

print(image_counts)

plt.figure(figsize = (10, 6))
sns.barplot(x = list(image_counts.keys()), y = list(image_counts.values()), palette ='viridis')
plt.title('Count of Images in Each Category')
plt.xlabel('Categories')
plt.ylabel('Number of Images')
plt.xticks(rotation = 45)
plt.show()

plt.figure(figsize = (8, 8))
plt.pie(image_counts.values(), labels = image_counts.keys(), autopct = '%1.1f%%', startangle = 140)
plt.title('Distribution of Images by Category')
plt.axis('equal')
plt.show()

def display_images_from_folders(base_dir, categories, num_images=5):
    plt.figure(figsize=(15, 10))

    for i, category in enumerate(categories):
        category_path = os.path.join(base_dir, category)
        image_files = [f for f in os.listdir(category_path) if f.endswith(('.bmp', '.jpg', '.png'))]

        for j, image_file in enumerate(image_files[:num_images]):

            img_path = os.path.join(category_path, image_file)
            image = cv2.imread(img_path)
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB

            plt.subplot(len(categories), num_images, i * num_images + j + 1)
            plt.imshow(image)
            plt.axis('off')
            plt.title(f"{category}")

    plt.tight_layout()
    plt.show()

display_images_from_folders(dataset, categories, num_images=5)

# Create an image_path-label mapping

def create_image_paths_dataframe(base_dir, categories):
    data = []

    for category in categories:
        category_path = os.path.join(base_dir, category)

        image_files = [f for f in os.listdir(category_path) if f.endswith(('.bmp', '.jpg', '.png'))]

        for image_file in image_files:
            img_path = os.path.join(category_path, image_file)
            data.append({'image_path': img_path, 'label': category})

    df_image_paths = pd.DataFrame(data)

    return df_image_paths

df_image_paths = create_image_paths_dataframe(dataset, categories)
print(df_image_paths.head())
print(df_image_paths.tail())

df_image_paths['label'].value_counts()

# Split the data into training, testing and validation sets for model training

def TrainValTestSplit(df_image_paths, output_dir, val_ratio=0.15, test_ratio=0.15):
    for split in ['train', 'val', 'test']:
        split_dir = os.path.join(output_dir, split)
        os.makedirs(split_dir, exist_ok=True)

    categories = df_image_paths['label'].unique()
    for split in ['train', 'val', 'test']:
        for category in categories:
            category_dir = os.path.join(output_dir, split, category)
            os.makedirs(category_dir, exist_ok=True)

    for category in categories:
        category_data = df_image_paths[df_image_paths['label'] == category]
        image_paths = category_data['image_path'].tolist()

        np.random.shuffle(image_paths)

        train_split = int(len(image_paths) * (1 - (val_ratio + test_ratio)))
        val_split = int(len(image_paths) * (1 - test_ratio))

        train_files = image_paths[:train_split]
        val_files = image_paths[train_split:val_split]
        test_files = image_paths[val_split:]

        def copy_with_dat(image_file, destination_dir):
            shutil.copy(image_file, destination_dir)
            base_name = os.path.splitext(os.path.basename(image_file))[0]
            dat_types = ['cyt.dat', 'nuc.dat']
            for dat_type in dat_types:
                dat_file = os.path.join(os.path.dirname(image_file), f"{base_name}_{dat_type}")
                if os.path.exists(dat_file):
                    shutil.copy(dat_file, destination_dir)

        for file in train_files:
            copy_with_dat(file, os.path.join(output_dir, 'train', category))

        for file in val_files:
            copy_with_dat(file, os.path.join(output_dir, 'val', category))

        for file in test_files:
            copy_with_dat(file, os.path.join(output_dir, 'test', category))

        print(f"{category}:")
        print(f"Total images: {len(image_paths)}")
        print(f"Training: {len(train_files)}")
        print(f"Validation: {len(val_files)}")
        print(f"Testing: {len(test_files)}")
        print()
output_dir = "/kaggle/working"
TrainValTestSplit(df_image_paths, output_dir, val_ratio=0.15, test_ratio=0.15)

# Verify the splitting went as expected or not

def display_images_from_split(output_dir, split, num_images=5):
    split_dir = os.path.join(output_dir, split)
    categories = [d for d in os.listdir(split_dir) if os.path.isdir(os.path.join(split_dir, d))]

    for category in categories:
        category_dir = os.path.join(split_dir, category)
        image_files = [f for f in os.listdir(category_dir) if f.endswith(('.bmp', '.jpg', '.png'))][:num_images]

        print(f"Split: {split}, Category: {category}")
        fig, axes = plt.subplots(1, len(image_files), figsize=(15, 5))
        for i, image_file in enumerate(image_files):
            img_path = os.path.join(category_dir, image_file)
            img = Image.open(img_path)
            axes[i].imshow(img)
            axes[i].axis('off')
            axes[i].set_title(image_file)
        plt.show()

for split in ['train', 'val', 'test']:
    display_images_from_split(output_dir, split, num_images=5)

"""Train transfer learning models"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from tensorflow.keras.applications import InceptionV3, MobileNetV2, InceptionResNetV2
from tensorflow.keras.layers import Dense, Flatten, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.metrics import classification_report, confusion_matrix
from scipy.spatial.distance import euclidean, cityblock, cosine

# Image augmentation
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    rotation_range=20
)
val_datagen = ImageDataGenerator(rescale=1.0/255)

train_data = train_datagen.flow_from_directory(
    '/kaggle/working/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)
val_data = val_datagen.flow_from_directory(
    '/kaggle/working/val',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

def plot_training_history(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']

    epochs = range(1, len(acc) + 1)

    # Plot accuracy
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, label='Training Accuracy', marker='o')
    plt.plot(epochs, val_acc, label='Validation Accuracy', marker='o')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    # Plot loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, label='Training Loss', marker='o')
    plt.plot(epochs, val_loss, label='Validation Loss', marker='o')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout()
    plt.show()

def plot_confusion_matrix(true_labels, predicted_labels, class_names):
    cm = confusion_matrix(true_labels, predicted_labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)

    plt.figure(figsize=(12, 8))
    disp.plot(cmap='Blues', values_format='d', ax=plt.gca())
    plt.xticks(rotation=45, fontsize=10, ha='right')
    plt.yticks(fontsize=10)
    plt.grid(False)
    plt.title('Confusion Matrix')
    plt.show()

def plot_roc_curve(true_labels, predicted_probs, class_names):

    # Binarize the true labels for ROC computation
    true_labels_binarized = label_binarize(true_labels, classes=np.arange(len(class_names)))

    # Compute ROC curve and AUC for each class
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(len(class_names)):
        fpr[i], tpr[i], _ = roc_curve(true_labels_binarized[:, i], predicted_probs[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    # Compute micro-average ROC curve and AUC
    fpr["micro"], tpr["micro"], _ = roc_curve(true_labels_binarized.ravel(), predicted_probs.ravel())
    roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

    # Compute macro-average ROC curve and AUC
    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(len(class_names))]))
    mean_tpr = np.zeros_like(all_fpr)
    for i in range(len(class_names)):
        mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])
    mean_tpr /= len(class_names)

    fpr["macro"] = all_fpr
    tpr["macro"] = mean_tpr
    roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

    # Plot all ROC curves
    plt.figure(figsize=(10, 7))

    # Individual class ROC curves
    for i, class_name in enumerate(class_names):
        plt.plot(fpr[i], tpr[i], lw=2, label=f'ROC curve for {class_name} (area = {roc_auc[i]:.2f})')
     # Micro-average ROC curve
    plt.plot(fpr["micro"], tpr["micro"],
             label=f'micro-average ROC curve (area = {roc_auc["micro"]:.2f})',
             color='deeppink', linestyle=':', linewidth=4)

    # Macro-average ROC curve
    plt.plot(fpr["macro"], tpr["macro"],
             label=f'macro-average ROC curve (area = {roc_auc["macro"]:.2f})',
             color='navy', linestyle=':', linewidth=4)

    # Plot settings
    plt.plot([0, 1], [0, 1], color='gray', linestyle='--', lw=2)
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend(loc='lower right')
    plt.grid(alpha=0.3)
    plt.show()

def evaluate_model(history, true_labels, predicted_labels, class_names, predictions):
    plot_training_history(history)
    plot_confusion_matrix(true_labels, predicted_labels, class_names)
    plot_roc_curve(true_labels, predictions, class_names)

"""Inception v3"""

def build_model(base_model):
    base_model.trainable = False  # Freeze pre-trained layers
    inputs = base_model.input
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128, activation='relu')(x)
    x = Dense(5, activation='softmax')(x) # Number of classes = 5
    model = Model(inputs, x)
    return model

checkpoint = ModelCheckpoint(
    'kaggle/working/checkpoints/inception_v3_model.keras',
    monitor='val_accuracy',
    save_best_only=True,
    mode='max',
    verbose=1
)

inception_v3_model = build_model(InceptionV3(weights='imagenet', include_top=False, input_shape=(224, 224, 3)))
inception_v3_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = inception_v3_model.fit(
    train_data,
    validation_data=val_data,
    epochs=20,
    callbacks=[checkpoint]
)

test_datagen = ImageDataGenerator(rescale=1.0/255)
test_data = test_datagen.flow_from_directory(
    '/kaggle/working/test',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle = False
)

predictions = inception_v3_model.predict(test_data)
predicted_classes = np.argmax(predictions, axis=1)

true_classes = test_data.classes
class_labels = list(test_data.class_indices.keys())

print("Classification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_labels))

# Verify predictions

test_images, test_labels = next(test_data)

batch_predictions = inception_v3_model.predict(test_images)
batch_predicted_classes = np.argmax(batch_predictions, axis=1)

for i in range(5):
    plt.imshow(test_images[i])
    plt.title(f"True: {class_labels[np.argmax(test_labels[i])]}, Pred: {class_labels[batch_predicted_classes[i]]}")
    plt.axis('off')
    plt.show()

evaluate_model(history, true_classes, predicted_classes, class_labels, predictions)

inception_v3_model.save('/kaggle/working/inception_v3_model.keras')

"""MobileNet v2"""

checkpoint = ModelCheckpoint(
    'kaggle/working/checkpoints/mobilenet_v2_model.keras',
    monitor='val_accuracy',
    save_best_only=True,
    mode='max',
    verbose=1
)

mobilenet_v2_model = build_model(MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3)))
mobilenet_v2_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history_mv2 = mobilenet_v2_model.fit(train_data, validation_data=val_data, epochs=20, callbacks=[checkpoint])

# Generate predictions
predictions = mobilenet_v2_model.predict(test_data)

# Convert predictions to class labels
predicted_classes = np.argmax(predictions, axis=1)

# Get true labels
true_classes = test_data.classes
class_labels = list(test_data.class_indices.keys())

# Print classification report
print("Classification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_labels))

evaluate_model(history_mv2, true_classes, predicted_classes, class_labels, predictions)

"""Inception Resnet v2"""

inception_resnet_v2_model = build_model(InceptionResNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3)))
inception_resnet_v2_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

checkpoint = ModelCheckpoint(
    'kaggle/working/checkpoints/inception_resnet_v2_model.keras',
    monitor='val_accuracy',
    save_best_only=True,
    mode='max',
    verbose=1
)

history_irv2 = inception_resnet_v2_model.fit(train_data, validation_data=val_data, epochs=20, callbacks=[checkpoint])

predictions = inception_resnet_v2_model.predict(test_data)
predicted_classes = np.argmax(predictions, axis=1)

true_classes = test_data.classes
class_labels = list(test_data.class_indices.keys())

print("Classification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_labels))

evaluate_model(history_irv2, true_classes, predicted_classes, class_labels, predictions)

"""Fuzzy-distance ensemble prediction"""

def fuzzy_ensemble(predictions):
    batch_size = predictions[0].shape[0]
    num_classes = predictions[0].shape[1]

    euclidean_distances = np.zeros((batch_size, num_classes))
    manhattan_distances = np.zeros((batch_size, num_classes))
    cosine_distances = np.zeros((batch_size, num_classes))

    for model_preds in predictions:
        for i in range(batch_size):
            for c in range(num_classes):
                ideal = np.zeros(num_classes)
                ideal[c] = 1  # Ideal vector for the current class

                euclidean_distances[i, c] += euclidean(model_preds[i], ideal)
                manhattan_distances[i, c] += cityblock(model_preds[i], ideal)
                cosine_distances[i, c] += cosine(model_preds[i], ideal)

    # Aggregate distances for fuzzy ensemble
    aggregated_distances = euclidean_distances * manhattan_distances * cosine_distances

    # Final prediction: class with the smallest aggregated distance
    final_predictions = np.argmin(aggregated_distances, axis=1)
    return final_predictions
test_predictions = [
    inception_v3_model.predict(test_data),
    mobilenet_v2_model.predict(test_data),
    inception_resnet_v2_model.predict(test_data)
]
final_predictions = fuzzy_ensemble(test_predictions)

true_classes = test_data.classes
class_labels = list(test_data.class_indices.keys())

print("Classification Report:")
print(classification_report(true_classes, final_predictions, target_names=class_labels))

plot_confusion_matrix(true_classes, final_predictions, class_labels)

import numpy as np
from sklearn.metrics import roc_curve, auc, cohen_kappa_score, classification_report
import matplotlib.pyplot as plt

def compute_roc_auc(y_true, y_scores):
    fpr, tpr, _ = roc_curve(y_true, y_scores)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend(loc='lower right')
    plt.show()

    return roc_auc

def compute_kappa(y_true, y_pred):
    return cohen_kappa_score(y_true, y_pred)

def compute_ncc_distance(predictions, centroids):
    distances = np.linalg.norm(predictions[:, np.newaxis] - centroids, axis=2)
    return np.argmin(distances, axis=1)

# Example usage (Replace with actual values)
y_true = np.random.randint(0, 2, 100)  # True labels
y_scores = np.random.rand(100)  # Predicted probabilities
y_pred = (y_scores > 0.5).astype(int)  # Convert to binary predictions

roc_auc_value = compute_roc_auc(y_true, y_scores)
kappa_value = compute_kappa(y_true, y_pred)
ncc_classifications = compute_ncc_distance(np.random.rand(100, 5), np.random.rand(5, 5))

print(f"ROC AUC: {roc_auc_value:.2f}")
print(f"Cohen's Kappa: {kappa_value:.2f}")
print(f"MCC Classifications: {ncc_classifications}")

import numpy as np
from scipy.spatial.distance import euclidean, cityblock, cosine

def fuzzy_membership(x):
    return np.exp(-x)  # Converts distance to fuzzy confidence score

def fuzzy_ensemble(predictions):
    batch_size = predictions[0].shape[0]
    num_classes = predictions[0].shape[1]

    fuzzy_scores = np.zeros((batch_size, num_classes))

    for model_preds in predictions:
        for i in range(batch_size):
            for c in range(num_classes):
                ideal = np.zeros(num_classes)
                ideal[c] = 1  # Ideal vector for the class

                # Compute distances
                euc_dist = euclidean(model_preds[i], ideal)
                manh_dist = cityblock(model_preds[i], ideal)
                cos_dist = cosine(model_preds[i], ideal)

                # Convert distances into fuzzy confidence scores
                fuzzy_scores[i, c] += fuzzy_membership(euc_dist) + fuzzy_membership(manh_dist) + fuzzy_membership(cos_dist)

    # Normalize scores across classes
    fuzzy_scores /= np.sum(fuzzy_scores, axis=1, keepdims=True)

    # Final prediction: class with the highest fuzzy score
    final_predictions = np.argmax(fuzzy_scores, axis=1)
    return final_predictions

# Test ensemble
test_predictions = [
    inception_v3_model.predict(test_data),
    mobilenet_v2_model.predict(test_data),
    inception_resnet_v2_model.predict(test_data)
]

final_predictions = fuzzy_ensemble(test_predictions)

import numpy as np
from scipy.spatial.distance import euclidean, cityblock, cosine
from sklearn.metrics import roc_curve, auc, cohen_kappa_score, f1_score, recall_score, accuracy_score
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

def fuzzy_membership(x):
    return np.exp(-x)  # Converts distance to fuzzy confidence score

def fuzzy_ensemble(predictions):
    batch_size = predictions[0].shape[0]
    num_classes = predictions[0].shape[1]

    fuzzy_scores = np.zeros((batch_size, num_classes))

    for model_preds in predictions:
        for i in range(batch_size):
            for c in range(num_classes):
                ideal = np.zeros(num_classes)
                ideal[c] = 1  # Ideal vector for the class

                # Compute distances
                euc_dist = euclidean(model_preds[i], ideal)
                manh_dist = cityblock(model_preds[i], ideal)
                cos_dist = cosine(model_preds[i], ideal)

                # Convert distances into fuzzy confidence scores
                fuzzy_scores[i, c] += fuzzy_membership(euc_dist) + fuzzy_membership(manh_dist) + fuzzy_membership(cos_dist)

    # Normalize scores across classes
    fuzzy_scores /= np.sum(fuzzy_scores, axis=1, keepdims=True)

    # Final prediction: class with the highest fuzzy score
    final_predictions = np.argmax(fuzzy_scores, axis=1)
    return final_predictions, fuzzy_scores

def compute_roc_auc(y_true, y_scores, num_classes):
    y_true_bin = label_binarize(y_true, classes=np.arange(num_classes))

    plt.figure(figsize=(8, 6))
    for i in range(num_classes):
        fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_scores[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve for Multiclass Classification')
    plt.legend()
    plt.show()

def compute_kappa(y_true, y_pred):
    return cohen_kappa_score(y_true, y_pred)

def compute_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    return accuracy, f1, recall

# Test ensemble
test_predictions = [
    inception_v3_model.predict(test_data),
    mobilenet_v2_model.predict(test_data),
    inception_resnet_v2_model.predict(test_data)
]

y_true = np.random.randint(0, 5, len(test_data))  # Replace with actual test labels
final_predictions, fuzzy_scores = fuzzy_ensemble(test_predictions)

compute_roc_auc(y_true, fuzzy_scores, num_classes=5)  # ✅ Now supports multiclass
kappa_value = compute_kappa(y_true, final_predictions)
accuracy, f1, recall = compute_metrics(y_true, final_predictions)

print(f"💡 ROC AUC Calculated!")
print(f"📌 Cohen's Kappa: {kappa_value:.2f}")
print(f"✅ Accuracy: {accuracy:.2f}")
print(f"🎯 F1-Score: {f1:.2f}")
print(f"🔄 Recall: {recall:.2f}")